### ISSUE TITLE
Background images get messed up when displayed in multiple windows

### ISSUE THREAD

**Issue by scharlton2** [i-RIC/prepost-gui#1060] opened 2022-09-09 17:31 UTC
### iRIC v4 (develop) 4.0.0.6848

1. Open [Ex3.ipro.zip](https://github.com/i-RIC/solver.fastmech/files/9537171/Ex3.ipro.zip) as Ex3.ipro.
2. Verify that checking and unchecking Background Images->r5img10.jpg and Background Images->r5img9.jpg behave as expected
3. Run the simulation
4. Calculation Result->Open new 2D Post-Processing Window
5. View->Tile Windows 

![image](https://user-images.githubusercontent.com/7538707/189402145-a0688201-8d75-4432-ae4f-f289192c9c10.png)

7. Check Images->r5img10.jpg in Post-processing (2D)

![image](https://user-images.githubusercontent.com/7538707/189402808-db4f2c33-1087-4ea4-9959-4f4dbfe4d3ce.png)

Note that the Pre-processing Window turns black.  This may be related to the Scalar update issue.  (Sometimes the images disappear completely and sometimes affects how the 'Grid shape' is displayed.

**Comment by scharlton2** [comment] 2022-10-26 17:23
Hi Keisuke,

It seems to still be a problem when I run Ex3.

![image](https://user-images.githubusercontent.com/7538707/198090300-7e928a1a-f65f-43ac-8fa9-6976b44d32ce.png)

Note that nothing is wrong until I check r5img10.jpg or r5img9.jpg (in the Post-prcessing (2D) window):

![image](https://user-images.githubusercontent.com/7538707/198091655-6877bb1c-3a32-490a-a62a-116dd601afbc.png)

It's strange that when I switch between the Pre and Post processing windows and Zoom in or out the other window goes black.

![image](https://user-images.githubusercontent.com/7538707/198093346-397da1cb-d92a-4f13-8392-a1cc5f702582.png)

Are you able to reproduce?

Thanks,
Scott

**Comment by kskinoue0612** [comment] 2022-10-28 09:22
Hi Scott,

Thank you for testing.

I've tested again on my PC, and when I build commit dc6205b, the problem is fixed, and all sub windows looks fine. I share the screenshot as below.

![screenshot_v4](https://user-images.githubusercontent.com/4031569/198551656-68d8d928-32b9-447f-a443-7ad50cda4370.png)

Not sure, but I'm afraid maybe I shared wrong branch.

I've noticed that I've accidently deleted issue-1060 branch from my repository. I've recovered issue-1060 branch now, and you can check from the following URL:

https://github.com/kskinoue0612/prepost-gui/tree/issue-1060

Can you make sure you've built commit dc6205b when you've tested?

Thank you,

Keisuke

**Comment by scharlton2** [comment] 2022-11-01 15:13
2022-11-01 -- Sorry Keisuke, I just noticed that I forgot to click the comment button.

Hi Keisuke,

I used the (appveyor) built version iRIC_v4_dev 4.0.0 Revision 6868 Released on 2022/10/26.  Can you try running that version?  I'm in training today so I'll try and run on another machine as soon as I can.

Thanks,
Scott

**Comment by scharlton2** [comment] 2022-11-01 16:22
Hi Keisuke,

While I was testing on a different machine, I noticed that the Post-processing Window (2D) was displaying the Grid->Node attributes->Elevation (from the pre-processor). 

![image](https://user-images.githubusercontent.com/7538707/199278600-77dba978-ccce-458b-a200-810fd12b7c9f.png)

This is also occurs on this version ([online_update_v4](https://github.com/i-RIC/online_update_v4)/iRIC_Installer_v4_dev.exe):

![image](https://user-images.githubusercontent.com/7538707/199281872-a9bc9e71-6614-4844-9150-c4559f7d4d4f.png)

Maybe something is not getting updated in the installer?  Or, maybe the same thing that you did for the background images needs to be done for everything?

Thanks,
Scott

**Comment by kskinoue0612** [comment] 2022-11-06 22:31
Hi Scott,

Thank you for checking, and I am sorry for late reply. It was holidays from
Thursday to Sunday.

I’ll look into the issues you’ve reported, and contacts you.

Thank you,

Keisuke

2022年11月2日(水) 1:22 Charlton, Scott R. ***@***.***>:

**Comment by kskinoue0612** [comment] 2022-11-09 04:49
Hi Scott,

Sorry that it took time.

I've checked, and noticed that the issue-1060 branch was not yet merged to develop_v4 branch. I've merged the branch so that you can check with iRIC v4 (develop).

Now the newest version of iRIC v4 (develop) is 4.0.0.6872. I've checked again, and made sure that it works fine with Ex3.

I hope it works for you this time.

Thank you,

Keisuke

**Comment by kskinoue0612** [comment] 2022-11-10 04:20
Hi Scott,

Thank you for checking. Glad to hear that it worked for you!

Yes, let’s talk about the Fastmech topic in the tomorrow meeting.

Thank you,

Keisuke

2022年11月10日(木) 7:55 Charlton, Scott R. ***@***.***>:

**Comment by kskinoue0612** [comment] 2022-11-21 01:24
Closed with #1082

**Closed by kskinoue0612** 2022-11-21 01:24 UTC
