### ISSUE TITLE
iRIC crashes in v4 when opening a file with 2d and 3d results

### ISSUE THREAD

**Issue by scharlton2** [i-RIC/prepost-gui#1034] opened 2022-05-17 18:31 UTC
Hi Keisuke,

This is related to https://github.com/i-RIC/iriclib_v4/issues/25 and https://github.com/i-RIC/iriclib_v4/issues/31.  If you run the included fastmech example in a  v3 version and open it with the v4 version it crashes iRIC.

Thanks
Scott

Updated fm-ex3 (with 3d results enabled)
[fm-ex3.zip](https://github.com/i-RIC/prepost-gui/files/8710372/fm-ex3.zip)

Latest prod version (3.0.19.6753)

![image](https://user-images.githubusercontent.com/7538707/168876455-d8eea55c-b5e0-4809-9e98-50c67cc3502a.png)

![image](https://user-images.githubusercontent.com/7538707/168876684-4068f4b0-c1f1-41a9-b3f8-f1d25634363e.png)

![image](https://user-images.githubusercontent.com/7538707/168881711-eb25c689-a73b-4400-a301-fa8ada964b69.png)

Open the same file with the latest v4 version (3.9.0.6821)

![image](https://user-images.githubusercontent.com/7538707/168880345-e609c368-751d-46d7-84b0-f44e75c12bcf.png)

![image](https://user-images.githubusercontent.com/7538707/168880441-95a36e66-e983-47ba-8362-ee638be3e51e.png)

iRIC crashes when opening

**Comment by scharlton2** [comment] 2022-05-17 21:43
Hi Keisuke,

I tried opening this 2d/3d solution in iRIC_v4 that I built on my local machine and it didn't crash.  The only thing I can think of is that there's some type of dll incompatibly problem.  Could you try running fm-ex3 in a prod or dev version and then try loading it into the latest iRIC_v4 (3.9.0.6821) version?

Thanks,
Scott

**Comment by kskinoue0612** [comment] 2022-05-18 23:22
Hi Scott,

Thank you for the information.
OK, I think I have time to test this today.

Thank you,

Keisuke

2022年5月18日(水) 6:43 Charlton, Scott R. ***@***.***>:

**Comment by scharlton2** [comment] 2022-05-22 19:08
Hi Keisuke,

Sorry to take so long, due to a change in VS2019, I had to fix iriclib_v4/python_binding (see https://github.com/i-RIC/iriclib_v4/runs/6479055384?check_suite_focus=true) and everything that depended on it.  I also added iriclib.dll to dist/CMakeLists.txt so that it is always up to date.  It seems to be working now.

Thanks,
Scott

**Comment by kskinoue0612** [comment] 2023-02-27 15:31
I close this because by updating iriclib, the issue is fixed.

**Closed by kskinoue0612** 2023-02-27 15:31 UTC
Labels: bug
